# Generated by Django 6.0.3 on 2026-03-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('customer',), name='unique_customer_main_address'),
        ),
    ]
